version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c maintenance_work_mem=256MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=64MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=10MB
      -c min_wal_size=256MB
      -c max_wal_size=1GB
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4
      -c log_statement=mod
      -c log_min_duration_statement=1000
    environment:
      POSTGRES_DB: ${DB_NAME:-drcrwell_db}
      POSTGRES_USER: ${DB_USER:-drcrwell_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_this_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drcrwell_user -d drcrwell_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --timeout 0
      --tcp-backlog 511
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M

  backend:
    image: ${DOCKER_USERNAME:-tomautomations}/drcrwell-backend:latest
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-drcrwell_user}
      DB_PASSWORD: ${DB_PASSWORD:-change_this_password}
      DB_NAME: ${DB_NAME:-drcrwell_db}
      DB_SSL_MODE: disable
      DB_MAX_OPEN_CONNS: ${DB_MAX_OPEN_CONNS:-50}
      DB_MAX_IDLE_CONNS: ${DB_MAX_IDLE_CONNS:-10}
      DB_CONN_MAX_LIFETIME: ${DB_CONN_MAX_LIFETIME:-3600}
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: 0
      # App
      ENV: production
      JWT_SECRET: ${JWT_SECRET:-change_this_secret_key_to_something_very_secure}
      PORT: 8080
      GIN_MODE: release
      CORS_ORIGINS: ${CORS_ORIGINS:-https://app.odowell.pro}
      # AWS S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-drcrwell-app}
      AWS_REGION: ${AWS_REGION:-sa-east-1}
      S3_BASE_FOLDER: ${S3_BASE_FOLDER:-exams}
      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-noreply@odowell.pro}
      FRONTEND_URL: https://${FRONTEND_URL:-app.odowell.pro}
      # App Branding
      APP_NAME: ${APP_NAME:-Sistema Odontológico}
    networks:
      - network_public
    deploy:
      replicas: ${BACKEND_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drcrwell-backend.rule=Host(`${BACKEND_URL:-api.odowell.pro}`)"
        - "traefik.http.routers.drcrwell-backend.entrypoints=websecure"
        - "traefik.http.routers.drcrwell-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.drcrwell-backend.loadbalancer.server.port=8080"
        - "traefik.docker.network=network_public"
        # Security headers middleware
        - "traefik.http.middlewares.drcrwell-security.headers.stsSeconds=63072000"
        - "traefik.http.middlewares.drcrwell-security.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.drcrwell-security.headers.stsPreload=true"
        - "traefik.http.middlewares.drcrwell-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.drcrwell-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.drcrwell-security.headers.frameDeny=true"
        - "traefik.http.routers.drcrwell-backend.middlewares=drcrwell-security"
    depends_on:
      - postgres
      - redis

  frontend:
    image: ${DOCKER_USERNAME:-tomautomations}/drcrwell-frontend:latest
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drcrwell-frontend.rule=Host(`${FRONTEND_URL:-app.odowell.pro}`)"
        - "traefik.http.routers.drcrwell-frontend.entrypoints=websecure"
        - "traefik.http.routers.drcrwell-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.drcrwell-frontend.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"
        # Security headers
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.stsSeconds=63072000"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.frameDeny=true"
        - "traefik.http.routers.drcrwell-frontend.middlewares=drcrwell-frontend-security"
    depends_on:
      - backend

networks:
  network_public:
    external: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
