version: '3.8'

# =============================================================================
# OdoWell Docker Stack - Production Configuration
# =============================================================================
# PostgreSQL foi migrado para VPS dedicada (5.78.93.61)
# O banco de dados agora roda nativamente na Worker VPS para melhor performance
# =============================================================================

services:
  # PostgreSQL removido - agora roda na Worker VPS (5.78.93.61)
  # Para restaurar o container local, descomente o serviço abaixo
  # e altere DB_HOST para 'postgres' no backend

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes", "--appendfsync", "everysec", "--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru", "--tcp-keepalive", "300", "--timeout", "0", "--save", "900 1", "--save", "300 10", "--save", "60 10000"]
    volumes:
      - redis_data:/data
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 2560M
        reservations:
          cpus: '0.25'
          memory: 512M

  backend:
    image: ${DOCKER_USERNAME:-tomautomations}/drcrwell-backend:latest
    environment:
      # Database (External - VPS 5.78.93.61)
      DB_HOST: 5.78.93.61
      DB_PORT: 5432
      DB_USER: ${DB_USER:-odowell_app}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-drcrwell_db}
      DB_SSL_MODE: require
      # Encryption Key for sensitive data
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRICE_BRONZE: ${STRIPE_PRICE_BRONZE}
      STRIPE_PRICE_SILVER: ${STRIPE_PRICE_SILVER}
      STRIPE_PRICE_GOLD: ${STRIPE_PRICE_GOLD}
      DB_MAX_OPEN_CONNS: ${DB_MAX_OPEN_CONNS:-80}
      DB_MAX_IDLE_CONNS: ${DB_MAX_IDLE_CONNS:-10}
      DB_CONN_MAX_LIFETIME: ${DB_CONN_MAX_LIFETIME:-3600}
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: 0
      # App
      ENV: production
      JWT_SECRET: ${JWT_SECRET}
      PORT: 8080
      GIN_MODE: release
      CORS_ORIGINS: ${CORS_ORIGINS:-https://app.odowell.pro}
      # AWS S3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-drcrwell-app}
      AWS_REGION: ${AWS_REGION:-sa-east-1}
      S3_BASE_FOLDER: ${S3_BASE_FOLDER:-exams}
      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-noreply@odowell.pro}
      FRONTEND_URL: https://${FRONTEND_URL:-app.odowell.pro}
      # App Branding
      APP_NAME: ${APP_NAME:-Sistema Odontológico}
      # Timezone
      TZ: ${TZ:-America/Sao_Paulo}
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: ${BACKEND_REPLICAS:-4}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drcrwell-backend.rule=Host(`${BACKEND_URL:-api.odowell.pro}`)"
        - "traefik.http.routers.drcrwell-backend.entrypoints=websecure"
        - "traefik.http.routers.drcrwell-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.drcrwell-backend.loadbalancer.server.port=8080"
        - "traefik.docker.network=network_public"
        # Security headers middleware
        - "traefik.http.middlewares.drcrwell-security.headers.stsSeconds=63072000"
        - "traefik.http.middlewares.drcrwell-security.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.drcrwell-security.headers.stsPreload=true"
        - "traefik.http.middlewares.drcrwell-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.drcrwell-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.drcrwell-security.headers.frameDeny=true"
        - "traefik.http.routers.drcrwell-backend.middlewares=drcrwell-security"
    depends_on:
      - redis

  frontend:
    image: ${DOCKER_USERNAME:-tomautomations}/drcrwell-frontend:latest
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 32M
      labels:
        - "traefik.enable=true"
        # Main frontend route (app.odowell.pro)
        - "traefik.http.routers.drcrwell-frontend.rule=Host(`${FRONTEND_URL:-app.odowell.pro}`)"
        - "traefik.http.routers.drcrwell-frontend.entrypoints=websecure"
        - "traefik.http.routers.drcrwell-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.drcrwell-frontend.loadbalancer.server.port=80"
        - "traefik.docker.network=network_public"
        # Patient Portal wildcard route (*.odowell.pro except reserved subdomains)
        - "traefik.http.routers.drcrwell-portal.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.odowell.pro`) && !Host(`app.odowell.pro`) && !Host(`api.odowell.pro`) && !Host(`www.odowell.pro`) && !Host(`port1979leoale.odowell.pro`)"
        - "traefik.http.routers.drcrwell-portal.entrypoints=websecure"
        - "traefik.http.routers.drcrwell-portal.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.drcrwell-portal.service=drcrwell-frontend"
        - "traefik.http.routers.drcrwell-portal.priority=1"
        # Security headers
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.stsSeconds=63072000"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.drcrwell-frontend-security.headers.frameDeny=true"
        - "traefik.http.routers.drcrwell-frontend.middlewares=drcrwell-frontend-security"
        - "traefik.http.routers.drcrwell-portal.middlewares=drcrwell-frontend-security"
    depends_on:
      - backend

networks:
  network_public:
    external: true

volumes:
  redis_data:
    driver: local
  # postgres_data e wal_archive removidos - DB agora na Worker VPS
